# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy entire MCP server source
COPY piperun-mcp-server/ ./

# Install dependencies, including devDependencies for building
RUN npm install

# Build the project and adjust permissions
RUN npm run build

# Expose port if needed (not required for stdio-based MCP)

ENTRYPOINT [ "node", "build/index.js" ]
